### PR TITLE
Storybook 5.0.0 Upgrade

### PR DESCRIPTION
**Pull request by tekdroid**
Hello! I had a need to use the addon in Storybook 5.0.0. It's only a few days old so I thought I would go ahead and take a stab at updating your addon to work with it. There was one main change that affected the addon, migrating from the now deprectaed onStory to on(STORY_CHANGED). This also required a change to the way the docs are stored and retrieved, using the new sanitized version of the kind/storyName as the storyId.

Please let me know if you have any questions or take issue with anything I've done. I needed this for work, so for now we are going to keep a version of this local to the project. When this PR is approved we will remove our fork and pull from the official package once again.

Thanks!

### CODE REVIEW

**Comment by jacobimpson** [comment]
👍  Would love a 5.0 fix to be implemented.

**Comment by tuchk4** [comment]
Thanls for you work. I realy appreciate it.

I made PR for `v5.0.0` but with breaking changes.
There are now `withDocs` or `withReadme` functions and no additional webpack configuration.

Also added some new awesome features like auto generating props table for react comopnents.

README is updated.


Instaed of

```js
storiesOf('Button', module).add(
  'Default',
  withReadme(ButtonReadme, () => (
    <Button onClick={action('clicked')} label="Hello Button" />
  )),
);
```

Use

```js
storiesOf('Button', module)
  .addParameters({
    readme: {
      content: ButtonReadme,
    },
  })
  .add('Default', () => (
    <Button onClick={action('clicked')} label="Hello Button" />
  ));
```

or

```js
storiesOf('Button', module).add(
  'Default',
  () => <Button onClick={action('clicked')} label="Hello Button" />,
  {
    readme: {
      content: ButtonReadme,
    },
  },
);
```


Here is issue #118 and pr #123

Not sure I will add compatibility with previous api but seems it is realy needed ...

**Comment by tuchk4** [comment]
We should decide if we need compatibility with prev api and then I will update your PR and merge into new version.

**Comment by tekdroid** [comment]
Sounds good, thanks for considering the changes. Let me know if I can make any further modifications to help, or if they aren't needed I understand as well. Once you include 5.x compatible in some form I will take your changes over mine and close my fork.

Best regards.

**Comment by tuchk4** [comment]
Close this PR.

Implementation according to new codebase moved to #125

**Pull request closed without merging**
