### PR TITLE
fix: undefined theme variable

### LINKED ISSUE #221: Theme error when using Storybook 5.3+
This is a follow up to issue  #220. I am having the same issue and I do not set a custom theme at all.  I had to add the following to make the error go away:

`addParameters({ options: { theme: {} } });`

### PR DESCRIPTION
**Pull request by matheus1lva**
fix #221 #228

### CODE REVIEW

**Comment by walkerdb** [comment]
cc @tuchk4 -- this fixes an issue a lot of users are seeing on latest storybook

**Comment by PlayMa256** [comment]
@walkerdb i've published fixing this under my repository. https://www.npmjs.com/package/storybook-readme-addon

i'll be maintaining that as we need fixes!

**Comment by tuchk4** [comment]
Sorry, for the super late merge :(

going to release a new version with the fix later today

**Comment by normancroan** [comment]
thanks @tuchk4 - a release today would be awesome!

**Comment by tylerjlawson** [comment]
Did this get released? If yes, which version? I am running into the related issue with v5.0.8

**Comment by tuchk4** [comment]
I thought it was released half-year ago...
Released it now.

I am still surprised that somebody uses `storybook-readme` since most of the features are available now out from the box

**Pull request merged**
